// apps/nextjs/src/components/contents/projects/ProjectCard.tsx
import { Project } from "@/libs/data/data";
import Card, { CardProps } from "@/components/cards/Card";
import CardOverlayAnchor from "@/components/cards/CardOverlayAnchor";

type ProjectCardProps = CardProps & {
  project: Project;
};

export default function ProjectCard({ project, ...props }: ProjectCardProps) {
  return (
    <Card {...props}>
      <div className="p-4">
        <CardOverlayAnchor href={`/projects/${project.slug}`}>
          <h1 className="text-xl font-black pb-2">{project.title}</h1>
        </CardOverlayAnchor>
        <p className="pb-2 text-sm text-neutral-500">
          {project.subtitle || ""}
        </p>
        <p className="truncate text-sm text-neutral-500">
          {project.tags.map((t) => t.text).join(" · ")}
        </p>
      </div>
    </Card>
  );
}

// apps/nuxt/components/contents/projects/ProjectCard.vue
<script setup lang="ts">
import type { Project } from "~/utils/data/data";

const props = defineProps<{
  project: Project;
}>();
</script>

<template>
  <CardsCard v-bind="$attrs">
    <div class="p-4">
      <CardsCardOverlayAnchor :to="`/projects/${props.project.slug}`">
        <h1 class="text-xl font-black pb-2">{{ props.project.title }}</h1>
      </CardsCardOverlayAnchor>
      <p class="pb-2 text-sm text-neutral-500">
        {{ props.project.subtitle || "" }}
      </p>
      <p class="truncate text-sm text-neutral-500">
        {{ props.project.tags.map((t) => t.text).join(" · ") }}
      </p>
    </div>
  </CardsCard>
</template>
