// apps/nextjs/src/components/contents/projects/ProjectCard.tsx
import { Project } from "@/libs/data/data";
import Card, { CardProps } from "@/components/cards/Card";
import CardOverlayAnchor from "@/components/cards/CardOverlayAnchor";

type ProjectCardProps = CardProps & {
  project: Project;
};

export default function ProjectCard({ project, ...props }: ProjectCardProps) {
  return (
    <Card {...props}>
      <div className="p-4">
        <CardOverlayAnchor href={`/projects/${project.slug}`}>
          <h1 className="text-xl font-black pb-2">{project.title}</h1>
        </CardOverlayAnchor>
        <p className="pb-2 text-sm text-neutral-500">
          {project.subtitle || ""}
        </p>
        <p className="truncate text-sm text-neutral-500">
          {project.tags.map((t) => t.text).join(" · ")}
        </p>
      </div>
    </Card>
  );
}

// apps/sveltekit/src/lib/components/contents/projects/ProjectCard.svelte
<script lang="ts">
	import Card from '$lib/components/cards/Card.svelte';
	import CardOverlayAnchor from '$lib/components/cards/CardOverlayAnchor.svelte';
	import ProjectContent from '$lib/components/contents/projects/ProjectContent.svelte';
	import type { Project } from '$lib/data/data';

	export let project: Project;
	const href = `/projects/${project.slug}`;
</script>

<Card>
	<div class="p-4">
		<CardOverlayAnchor {href}>
			<h1 class="text-xl font-black pb-2">{project.title}</h1>
			<ProjectContent slot="dialog" {project} />
		</CardOverlayAnchor>
		<p class="pb-2 text-sm text-neutral-500">{project.subtitle || ''}</p>
		<p class="truncate text-sm text-neutral-500">{project.tags.map((t) => t.text).join(' · ')}</p>
	</div>
</Card>
