// apps/nuxt/components/contents/projects/ProjectsSection.vue
<script setup lang="ts">
import { getProjects } from "~/utils/data/data";

const projects = await getProjects({ count: 8 });
</script>

<template>
  <section class="container mx-auto px-2 py-8">
    <h2 class="font-black text-2xl pb-8">Projects</h2>
    <ul class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
      <li v-for="project in projects" :key="project.slug">
        <ContentsProjectsProjectCard :project="project" />
      </li>
    </ul>
    <NuxtLink class="w-full text-center block p-4 mt-4" to="/projects">
      All projects →
    </NuxtLink>
  </section>
</template>

// apps/sveltekit/src/lib/components/contents/projects/ProjectsSection.svelte
<script lang="ts">
	import ProjectCard from '$lib/components/contents/projects/ProjectCard.svelte';
	import type { Project } from '$lib/data/data';
	import ProjectCardLoading from './ProjectCardLoading.svelte';
	export let projects: Promise<Project[]>;
</script>

<section class="container mx-auto px-2 py-8">
	<h2 class="font-black text-2xl pb-8">Projects</h2>
	<ul class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
		{#await projects}
			{#each { length: 8 } as _, i}
				<li>
					<ProjectCardLoading />
				</li>
			{/each}
		{:then projects}
			{#each projects as project (project.slug)}
				<li>
					<ProjectCard {project} />
				</li>
			{/each}
		{/await}
	</ul>
	<a class="w-full text-center block p-4 mt-4" href="/projects"> All projects → </a>
</section>
