// apps/nuxt/components/contents/posts/PostContent.vue
<script setup lang="ts">
import { getPosts } from "~/utils/data/data";
import dateformat from "dateformat";

const props = defineProps<{
  slug: string;
}>();

const [post] = await getPosts({ slug: props.slug });

useHead({
  title: post.title,
  meta: [
    {
      name: "description",
      content: post.description,
    },
  ],
});
</script>

<template>
  <div class="prose lg:prose-md dark:prose-invert mx-auto">
    <h1 class="pt-8 m-0">{{ post.title }}</h1>
    <span class="block pt-8 text-md text-neutral-500">
      {{ dateformat(new Date(post.publishedTime), "dd mmm yyyy") }} ·{{ " " }}
      {{ post.keywords || "" }}
    </span>
    <div class="pt-4">
      <MDXContent :content="post.content">
        <template #fallback>
          <p>
            <SkeletonsTextSkeleton className="w-full" />
          </p>
          <p>
            <SkeletonsTextSkeleton className="w-full" />
          </p>
          <p>
            <SkeletonsTextSkeleton className="w-full" />
          </p>
        </template>
      </MDXContent>
    </div>
  </div>
</template>

// apps/sveltekit/src/lib/components/contents/posts/PostContent.svelte
<script lang="ts">
	import MDXContent from '$lib/components/mdx/MDXContent.svelte';
	import type { Post } from '$lib/data/data';
	import dateformat from 'dateformat';

	export let post: Post;
</script>

<div class="prose lg:prose-md dark:prose-invert mx-auto">
	<h1 class="pt-8 m-0">{post.title}</h1>
	<span class="block pt-8 text-md text-neutral-500">
		{dateformat(new Date(post.publishedTime), 'dd mmm yyyy')} ·{' '}
		{post.keywords || ''}
	</span>
	<div class="pt-4">
		<MDXContent content={post.content} />
	</div>
</div>
