// apps/nuxt/components/contents/photos/PhotosList.vue
<script setup lang="ts">
import { getPhotos } from "~/utils/data/data";

const photos = await getPhotos();
</script>

<template>
  <h1 class="text-3xl font-black px-4 py-4">Photography</h1>
  <ul class="grid grid-cols-1 gap-4 px-2 py-4 md:grid-cols-2 lg:grid-cols-4">
    <li v-for="photo in photos" :key="photo.slug">
      <ContentsPhotosPhotoCard :photo="photo" />
    </li>
  </ul>
</template>

// apps/nextjs/src/components/contents/photos/PhotosList.tsx
import PhotoCard from "./PhotoCard";
import { getPhotos } from "@/libs/data/data";

export default async function PhotosList() {
  const photos = await getPhotos();

  return (
    <>
      <h1 className="text-3xl font-black px-4 py-4">Photography</h1>
      <ul className="grid grid-cols-1 gap-4 px-2 py-4 md:grid-cols-2 lg:grid-cols-4">
        {photos.map((photo) => (
          <li key={photo.slug}>
            <PhotoCard photo={photo} />
          </li>
        ))}
      </ul>
    </>
  );
}
