// apps/nextjs/src/components/contents/photos/PhotosSection.tsx
import { getPhotos } from "@/libs/data/data";
import { Link } from "react-transition-progress/next";
import PhotoCard from "./PhotoCard";

export default async function PhotosSection() {
  const photos = await getPhotos({ count: 8 });

  return (
    <section className="container mx-auto px-2 py-8">
      <h2 className="font-black text-2xl pb-8">Photography</h2>
      <ul className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
        {photos.map((p) => (
          <li key={p.slug}>
            <PhotoCard photo={p} />
          </li>
        ))}
      </ul>
      <Link className="w-full text-center block p-4 mt-4" href="/photography">
        All photography →
      </Link>
    </section>
  );
}

// apps/nuxt/components/contents/photos/PhotosSection.vue
<script setup lang="ts">
import { getPhotos } from "~/utils/data/data";

const photos = await getPhotos({ count: 8 });
</script>

<template>
  <section class="container mx-auto px-2 py-8">
    <h2 class="font-black text-2xl pb-8">Photography</h2>
    <ul class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
      <li v-for="photo in photos" :key="photo.slug">
        <ContentsPhotosPhotoCard :photo="photo" />
      </li>
    </ul>
    <NuxtLink class="w-full text-center block p-4 mt-4" to="/photography">
      All photography →
    </NuxtLink>
  </section>
</template>
