// apps/sveltekit/src/lib/components/contents/photos/PhotoCard.svelte
<script lang="ts">
	import Card from '$lib/components/cards/Card.svelte';
	import CardOverlayAnchor from '$lib/components/cards/CardOverlayAnchor.svelte';
	import FilledImage from '$lib/components/images/FilledImage.svelte';
	import type { Photo } from '$lib/data/data';
	import dateformat from 'dateformat';
	import PhotoContent from './PhotoContent.svelte';
	import { getRemoteImagePath } from '$lib/data/image';
	export let photo: Photo;
</script>

<Card {...$$props}>
	<FilledImage
		className="object-cover"
		alt={photo.place}
		src={getRemoteImagePath(`/photos/${photo.slug}.jpeg`)}
		placeholder={photo.blurDataURL}
	/>
	<div class="p-2">
		<CardOverlayAnchor href={`/photography/${photo.slug}`}>
			<h1 class="font-black">{photo.place}</h1>
			<PhotoContent slot="dialog" {photo} />
		</CardOverlayAnchor>
		{#if photo.date}
			<p class="text-neutral-500 text-sm">
				{[dateformat(new Date(photo.date), 'dd mmm yyyy'), photo.camera]
					.filter((x) => x)
					.join(' · ')}
			</p>
		{/if}
	</div>
</Card>

// apps/nuxt/components/contents/photos/PhotoCard.vue
<script setup lang="ts">
import type { Photo } from "~/utils/data/data";
import dateformat from "dateformat";
import { getRemoteImagePath } from "~/utils/data/image";

const props = defineProps<{
  photo: Photo;
}>();

function formatDate(date: string | undefined) {
  return date ? dateformat(new Date(date), "dd mmm yyyy") : "";
}
</script>

<template>
  <CardsCard v-bind="$attrs">
    <ImagesFilledImage
      width="250"
      :alt="props.photo.place"
      :src="getRemoteImagePath(`/photos/${props.photo.slug}.jpeg`)"
    />
    <div class="p-2">
      <CardsCardOverlayAnchor :href="`/photography/${props.photo.slug}`">
        <h1 class="font-black">{{ props.photo.place }}</h1>
      </CardsCardOverlayAnchor>
      <p v-if="props.photo.date" class="text-neutral-500 text-sm">
        {{
          [formatDate(props.photo.date), props.photo.camera]
            .filter(Boolean)
            .join(" · ")
        }}
      </p>
    </div>
  </CardsCard>
</template>
