// apps/sveltekit/src/lib/components/contents/projects/ProjectsList.svelte
<script lang="ts">
	import ProjectCard from '$lib/components/contents/projects/ProjectCard.svelte';
	import type { Project } from '$lib/data/data';
	import ProjectCardLoading from './ProjectCardLoading.svelte';
	export let projects: Promise<Project[]>;
</script>

<h1 class="text-3xl font-black px-4 py-4">Projects</h1>
<ul class="grid grid-cols-1 gap-4 px-2 py-4 md:grid-cols-2 lg:grid-cols-4">
	{#await projects}
		{#each { length: 8 } as _, i}
			<li>
				<ProjectCardLoading />
			</li>
		{/each}
	{:then projects}
		{#each projects as project (project.slug)}
			<li>
				<ProjectCard {project} />
			</li>
		{/each}
	{/await}
</ul>

// apps/nextjs/src/components/contents/projects/ProjectsList.tsx
import ProjectCard from "@/components/contents/projects/ProjectCard";
import { getProjects } from "@/libs/data/data";

export default async function ProjectsList() {
  const projects = await getProjects();
  return (
    <>
      <h1 className="text-3xl font-black px-4 py-4">Projects</h1>
      <ul className="grid grid-cols-1 gap-4 px-2 py-4 md:grid-cols-2 lg:grid-cols-4">
        {projects.map((project) => (
          <li key={project.slug}>
            <ProjectCard project={project} />
          </li>
        ))}
      </ul>
    </>
  );
}
