// apps/nuxt/components/contents/projects/ProjectsSection.vue
<script setup lang="ts">
import { getProjects } from "~/utils/data/data";

const projects = await getProjects({ count: 8 });
</script>

<template>
  <section class="container mx-auto px-2 py-8">
    <h2 class="font-black text-2xl pb-8">Projects</h2>
    <ul class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
      <li v-for="project in projects" :key="project.slug">
        <ContentsProjectsProjectCard :project="project" />
      </li>
    </ul>
    <NuxtLink class="w-full text-center block p-4 mt-4" to="/projects">
      All projects →
    </NuxtLink>
  </section>
</template>

// apps/nextjs/src/components/contents/projects/ProjectsSection.tsx
import ProjectCard from "./ProjectCard";
import { getProjects } from "@/libs/data/data";
import { Link } from "react-transition-progress/next";

export default async function ProjectsSection() {
  const projects = await getProjects({ count: 8 });

  return (
    <section className="container mx-auto px-2 py-8">
      <h2 className="font-black text-2xl pb-8">Projects</h2>
      <ul className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
        {projects.map((p) => (
          <li key={p.slug}>
            <ProjectCard key={p.slug} project={p} />
          </li>
        ))}
      </ul>
      <Link className="w-full text-center block p-4 mt-4" href="/projects">
        All projects →
      </Link>
    </section>
  );
}
